### ISSUE TITLE
Player Filter on RPI plot

### ISSUE THREAD

**Issue by benjamtre** [tjconstant/FantasyEPL#3]
Hi Tom,

I think it would be really useful to be able to filter by player, particularly on the RPI plot. I'm interested to see how everyone else has been doing without being swamped by my excellent performance in GW20.

Cheers!

**Comment by tjconstant** [comment]
To clarify, is this a simple 'hide/show a manager' type interactivity (easy) or a 'recalculate the averages' interactivity (hard)?

**Comment by benjamtre** [comment]
A hide/show would be great.

**Comment by tjconstant** [comment]
Phew, super easy! Updated just now, click legend to remove player, double-click a legend item to isolate that trace.
